dist: xenial   # required for Python >= 3.7
language: python
python:
  # - "3.5" - incompatible due to use of type hints
  - "3.6"
  - "3.7"
  - "2.7"
  # PyPy versions
  - "pypy"
  # - "pypy3.5" - incompatible
  # - "pypy3" - deactivate. Although tests passes, TravisCI has some issues/bugs with PyPy3.6 as build hangs after tests passed
before_script: pip install coveralls
install:
  - "pip install '.[test]'"
script:
  - "python run_tests.py"
  - "coverage run --branch --include=./py2/pyxtension/Json.py,./py2/pyxtension/streams.py --omit=./py2/pyxtension/tests/* run_tests.py"
after_success:
  - coveralls