language: python
python:
#  - "3.4"
#  - "3.3"
#  - "3.2"
  - "3.6"
  - "2.7"
  - "2.6"
  - "pypy"
#  - "pypy3"
before_script: pip install coveralls
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install -r requirements-test.txt; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install -r requirements-test.txt; fi
  - if [[ $TRAVIS_PYTHON_VERSION == pypy ]]; then pip install -r requirements-test.txt; fi
  - "python setup.py install"
script:
  - "python run_tests.py"
  - "python install_test.py"
#  - "python -m unittest tests.test_Json tests.test_Streams"
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; coverage run --branch --include=./py2/pyxtension/Json.py,./py2/pyxtension/streams.py --omit=./py2/pyxtension/tests/* run_tests.py; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; coverage run --branch --include=./py3/pyxtension/Json.py,./py3/pyxtension/streams.py --omit=./py3/pyxtension/tests/* run_tests.py; fi

after_success:
  - coveralls