language: python
python:
#  - "3.4"
#  - "3.3"
#  - "3.2"
  - "2.7"
  - "2.6"
  - "pypy"
#  - "pypy3"
before_script: pip install coveralls
install:
  - "pip install -r requirements-tests.txt"
  - "python setup.py install"
script:
  - "python -m unittest tests.test_Json tests.test_Streams"
  - "coverage run --branch --include=./pyxtension/Json.py,./pyxtension/streams.py --omit=tests/* -m unittest tests.test_Json tests.test_Streams tests.test_abstractSynchronizedBufferedStream  tests.test_synchronizedBufferedStream"
after_success:
  - coveralls