dist: xenial   # required for Python >= 3.7
language: python
python:
#  - "3.4"
#  - "3.3"
#  - "3.2"
  - "3.6"
  - "3.7"
  - "2.7"
  # PyPy versions
  - "pypy"
  - "pypy3.6"
before_script: pip install coveralls
install:
  - "python setup.py install"
script:
  - "python run_tests.py"
  - "python install_test.py"
  - "coverage run --branch --include=./py2/pyxtension/Json.py,./py2/pyxtension/streams.py --omit=./py2/pyxtension/tests/* run_tests.py"
after_success:
  - coveralls