language: python
python:
#  - "3.4"
#  - "3.3"
#  - "3.2"
  - "2.7"
  - "2.6"
  - "pypy"
#  - "pypy3"
#install:
#  - "pip install -r requirements-tests.txt"
#  - "python setup.py install"
before_script: pip install coveralls
script:
  - "python -m unittest tests.test_Json tests.test_Streams"
  - "coverage.exe run --branch --include=./*.py --omit=tests/* -m unittest tests.test_Json tests.test_Streams"
after_success:
  - coveralls